name: Build client server without running Unit tests

on:
  # This workflow can be triggered manually from the GitHub Actions page
  workflow_dispatch:
    inputs:
      previous_run_id:
        description: 'Run id to download the docker image artifact:'
        required: false
        type: string
        default: "0"
  repository_dispatch:
    types: [ ci-test-limit-command ]

jobs:
  setup-params:
    runs-on: ubuntu-latest
    outputs:
      pr: ${{steps.args.outputs.pr}}
      runId: ${{steps.args.outputs.runId}}
    steps:
      - name: Set args
        id: args
        run: |
          if [[ ${{github.event_name}} == 'repository_dispatch' ]]; then
            echo "pr=${{ github.event.client_payload.pull_request.number }}" >> $GITHUB_OUTPUT
            checkArg=`echo ${{toJSON(github.event.client_payload.slash_command.args.named)}} | jq 'has("runId")'`
            cat $checkArg
            if [[ $checkArg != 'false' ]]
              echo "runId=${{ github.event.client_payload.slash_command.args.named.runId }}" >> $GITHUB_OUTPUT
            else
              echo "runId=0" >> $GITHUB_OUTPUT
            fi
          else
            echo "runId=${{ inputs.previous_run_id }}" >> $GITHUB_OUTPUT
            echo "pr=0" >> $GITHUB_OUTPUT
          fi
         
  server-build:
    name: server-build
    uses: ./.github/workflows/server-build.yml
    secrets: inherit
    with:
      pr: 0
      skip-tests: "true"

  client-build:
    name: client-build
    uses: ./.github/workflows/client-build.yml
    secrets: inherit
    with:
      pr: 0
      skip-tests: "true"

  rts-build:
    name: rts-build
    uses: ./.github/workflows/rts-build.yml
    secrets: inherit
    with:
      pr: 0
      
  build-docker-image:
    needs: [ client-build, server-build, rts-build ]
    # Only run if the build step is successful
    if: success()
    name: build-docker-image
    uses: ./.github/workflows/build-docker-image.yml
    secrets: inherit
    with:
      pr: 0

  ci-test-limited:
    needs: [ build-docker-image ]
    # Only run if the build step is successful
    if: success()
    name: ci-test-limited
    uses: ./.github/workflows/ci-test-limited.yml
    secrets: inherit
    with:
      pr: 0
