name: Testing my custom solutions

on:
  # This line enables manual triggering of this workflow.
  workflow_dispatch:

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print run attempt
        run : echo "failed-spec-${{github.run_attempt}}"
        
      - name: Print previous run attempt
        run : echo "failed_spec_artifact=failed-spec-ci-$((${{github.run_attempt}}-1))" >> $GITHUB_ENV
      - run : echo "${{env.failed_spec_artifact}}"
