name: Testing my custom solutions

on:
  # This line enables manual triggering of this workflow.
  workflow_dispatch:

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print run attempt
        run : echo "failed-spec-${{github.run_attempt}}"
        
      - name: Print previous run attempt
        run : echo "failed_spec_artifact=failed-spec-ci-$((${{github.run_attempt}}-1))" >> $GITHUB_ENV
      - name: Restore the previous failed combine result
        if: steps.run_result.outputs.run_result == 'failedtest'
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.failed_spec_artifact }}
          path: ~/failed_spec_ci
